version: '3.5'
services:
  db_auth:
    container_name: db_auth
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin1
      - POSTGRES_USER=admin
    image: postgres:16.0-alpine3.18